import { ArrowRight, Check, ClipboardCheck, Gauge, ShieldCheck, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import "./financial-profile-improvement.css";

const focus=[
  {icon:ClipboardCheck,title:"Credit & Profile Review",text:"Review the factors affecting your current borrowing position and identify items that may be limiting financing options."},
  {icon:ShieldCheck,title:"Profile Improvement",text:"Create a focused plan to address credit and financial-profile issues that may be standing between you and stronger approvals."},
  {icon:Gauge,title:"Funding Readiness",text:"Strengthen the overall profile lenders evaluate so future financing conversations begin from a better position."},
  {icon:TrendingUp,title:"Return to Capital",text:"The objective is not improvement for its own sake. It is to build toward better access to business and investment capital."}
];

export default function FinancialProfileImprovement(){return <main className="fpi-page">
  <section className="fpi-hero"><div className="container fpi-hero-grid"><div><p className="section-kicker light">FINANCIAL PROFILE IMPROVEMENT</p><h1>Strengthen the Profile Behind the Approval.</h1><p>When financing is limited by credit or other financial-profile factors, the next step may not be another application. KP Capital Solutions helps you understand what may be holding you back, strengthen your position and work toward better funding readiness.</p><div className="actions"><a className="btn btn-gold" href="https://capital.kpcapitalsolutions.com/">Begin Your Profile Review <ArrowRight size={18}/></a><Link className="btn btn-outline" to="/capital-strategy">Explore Capital Strategy</Link></div></div><div className="fpi-hero-card"><ShieldCheck/><span>THE PURPOSE</span><strong>Improve the profile.<br/>Strengthen fundability.<br/>Build toward capital.</strong><p>This is not positioned as a stand-alone credit repair service. It is part of a broader strategy to improve financial readiness and create stronger financing options.</p></div></div></section>

  <section className="fpi-intro"><div className="container fpi-intro-grid"><div><p className="section-kicker">WHEN FUNDING ISN'T READY YET</p><h2>A Decline Should Create Direction, Not More Applications.</h2></div><div><p>Repeatedly applying for financing without understanding the underlying issue can create frustration without improving the outcome. The better approach is to identify the factors affecting the profile and address them deliberately.</p><p>Financial Profile Improvement is designed for clients who know—or discover through an assessment—that credit or other profile issues need attention before pursuing the next level of financing.</p></div></div></section>

  <section className="fpi-focus"><div className="container"><div className="fpi-heading"><p className="section-kicker">A STRONGER PATH FORWARD</p><h2>Improvement With a Funding Objective.</h2><p>The work stays connected to the larger goal: creating a stronger position for future capital.</p></div><div className="fpi-grid">{focus.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

  <section className="fpi-journey"><div className="container fpi-journey-grid"><div><p className="section-kicker light">HOW IT FITS TOGETHER</p><h2>Assessment First. Improvement When Needed. Funding When Ready.</h2><p>The assessment helps determine where you stand. If your profile is ready, the conversation can move toward financing. If it needs work, Financial Profile Improvement provides a structured path to strengthen the areas affecting fundability.</p><ul><li><Check/>Assess your current position and capital objective</li><li><Check/>Identify profile factors affecting financing</li><li><Check/>Work through a focused improvement strategy</li><li><Check/>Reevaluate funding readiness as the profile strengthens</li><li><Check/>Return to appropriate financing when positioned to do so</li></ul></div><div className="fpi-flow"><div><span>01</span><strong>ASSESS</strong><p>Understand where you stand.</p></div><div><span>02</span><strong>IMPROVE</strong><p>Address what is limiting the profile.</p></div><div><span>03</span><strong>PREPARE</strong><p>Build stronger funding readiness.</p></div><div><span>04</span><strong>FUND</strong><p>Pursue the right capital when ready.</p></div></div></div></section>

  <section className="fpi-distinction"><div className="container"><p className="section-kicker">THE DIFFERENCE</p><h2>The Goal Isn't a Better Number.<br/>It's a Better Financial Position.</h2><p>Credit can be an important part of fundability, but it is not the entire capital strategy. We keep the focus on the bigger picture: stronger borrowing readiness, better financing choices and greater access to capital over time.</p></div></section>

  <section className="final-cta fpi-cta"><div className="container"><p className="section-kicker light">READY TO STRENGTHEN YOUR POSITION?</p><h2>Build Toward Better Funding Options.</h2><p>If you already know your financial profile needs attention, begin the profile review. If you're not sure where you stand, start with the assessment first.</p><div className="actions centered"><a className="btn btn-gold" href="https://capital.kpcapitalsolutions.com/">Begin Your Profile Review <ArrowRight size={18}/></a><a className="btn btn-outline" href="https://kpcapitalfunding.com/#/free-calculator">Start Your Assessment</a></div></div></section>
</main>}
